=== Cogax/JavaSaxDomParserExample/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="connections">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="connection">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="date" type="xs:date"/>
              <xs:element name="from" type="destination"/>
              <xs:element name="to" type="destination"/>
              <xs:element ref="train"/>
              <xs:element ref="capacity"/>
              <xs:element ref="note" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="train">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="2"/>
        <xs:maxLength value="20"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="capacity">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="firstClass" type="capacitySelection"/>
        <xs:element name="secondClass" type="capacitySelection"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="note">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:maxLength value="200"/>
        </xs:restriction>
      </xs:simpleType>
  </xs:element>
  
  <!-- type: destination -->
  <xs:complexType name="destination">
    <xs:sequence>
      <xs:element name="station">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="2"/>
            <xs:maxLength value="150"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="time" type="xs:time"/>
      <xs:element name="track" type="xs:positiveInteger"/>
    </xs:sequence>  
  </xs:complexType>
  
  <!-- type: capacitySelection -->
  <xs:simpleType name="capacitySelection">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="3"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Cogax/JavaSaxDomParserExample/src/test/resources/notValidTrain.xml
<?xml version="1.0" encoding="UTF-8"?>
<connections xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schema.xsd">
  <connection>
    <date>2014-12-01</date>
    <from>
      <station>St. Gallen</station>
      <time>12:11:00</time>
      <track>1</track>  
    </from>
    <to>
      <station>Zürich</station>
      <time>15:11:00</time>
      <track>1</track>  
    </to>
    <train>ICNICNICNICNICNICNICNICNICNICNICNICNICNICNICNICNICNICNICNICNIC</train>
    <capacity>
      <firstClass>1</firstClass>  
      <secondClass>3</secondClass>
    </capacity>
    <note>Richtung: Genève</note>
  </connection>
</connections>

=== Cogax/JavaSaxDomParserExample/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<connections xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/andy/Projects/xmlExample/schema.xsd">
  <connection>
    <date>2014-12-01</date>
    <from>
      <station>St. Gallen</station>
      <time>12:11:00</time>
      <track>1</track>  
    </from>
    <to>
      <station>St. Gallen</station>
      <time>12:11:00</time>
      <track>1</track>  
    </to>
    <train>ICN</train>
    <capacity>
      <firstClass>1</firstClass>  
      <secondClass>3</secondClass>
    </capacity>
    <note>Richtung: Genève</note>
  </connection>
</connections>
